name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material pillow cairosvg mkdocs-awesome-pages-plugin mike mkdocs-charts-plugin
      # Build MkDocs projects in subdirectories
      - run: cd docs/2nd_sem
      - run: mkdocs build
      - run: cd ../3rd_sem
      - run: mkdocs build
      - run: cd ../4th_sem
      - run: mkdocs build
      - run: cd ../..
      - run: mkdocs build
      # Deploy to GitHub Pages
      - run: mkdocs gh-deploy --force
      # Uncomment and use the following if you have a custom domain
      # - run: echo "collegehive.in" > ./site/CNAME
