name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material pillow cairosvg mkdocs-awesome-pages-plugin mike mkdocs-charts-plugin
      # Build MkDocs projects in subdirectories
      - run: cd docs/2nd_sem && mkdocs build && cd ../3rd_sem && mkdocs build && cd ../4th_sem && mkdocs build && cd ../.. && mkdocs build
      # create sitemap for SEO
      - run: python3 docs/sitemap.py
      # Deploy to GitHub Pages
      # - run: mkdocs gh-deploy --force
      
      - run: git checkout -B gh-pages
        # Assuming your index.html is in the root directory after mkdocs build
        # You can adjust the path as necessary
      - run:  cp index.html site/
      - run:  cd site
      - run:  git add .
      - run:  git commit -m "Deploy to GitHub Pages"
      - run:  git push origin gh-pages --force
      # Uncomment and use the following if you have a custom domain
      # - run: echo "collegehive.in" > ./site/CNAME
